name: drt1
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  ffigen: ^6.0.1
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  convert: ^3.0.2
  ffi: ^2.0.1
  sembast: ^3.2.0+1
ffigen:
  output: 'lib/generated_bindings.dart'
  headers:
    entry-points:
      - '/Users/alek/src/go-iden3-core-clib/ios/libiden3core.h'
